---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization  
namespace: street-merchant-server

resources:
- base/00-namespace.yml
- server/01-deployment.yml

secretGenerator:
- name: street-merchant-server-env
  # env is a path to a file to read lines of key=val
  # you can only specify one env file per secret.   
  # For setting up your env.txt file please see: https://github.com/jef/streetmerchant/blob/main/.env-example
  env: secrets/env.txt
  type: Opaque

    